local ls = require("luasnip") -- 引入 LuaSnip

-- 定义一些快捷函数
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local d = ls.dynamic_node
local sn = ls.snippet_node
local fmt = require("luasnip.extras.fmt").fmt
ls.add_snippets("cpp", {
    s("acm", {
        t({ "#include <bits/stdc++.h>",
            "using namespace std;",
            "using i64 = long long;",
            "",
            "int main() {",
            "\tcin.tie(nullptr);",
            "\tios::sync_with_stdio(false);",
            "",
            "\t" }), i(1), -- 插入点 1
        t({ "", "",
            "\treturn 0;",
            "",
            "}" }),
    }),
    s("acms", {
        t({ "#include <bits/stdc++.h>",
            "using namespace std;",
            "using i64 = long long;",
            "" }),
        t({ "", "void solve() {" }),
        t({ "", "\t" }), i(1, ""),
        t({ "", "}", "" }),
        t({ "", "int main() {",
            "\tcin.tie(nullptr);",
            "\tios::sync_with_stdio(false);" }),
        t({ "", "\tint t; cin >> t;" }),
        t({ "", "\twhile (t--) { solve(); }" }),
        t({ "", "\treturn 0;", }),
        t({ "", "}" }),
    }),
    s("DSU", {
        t({ "struct DSU {",
            "\tstd::vector<int> f, siz;",
            "\t",
            "\tDSU() {}",
            "\tDSU(int n) {",
            "\t\tinit(n);",
            "\t}",
            "\tvoid init(int n) {",
            "\t\tf.resize(n);",
            "\t\tstd::iota(f.begin(), f.end(), 0);",
            "\t\tsiz.assign(n, 1);",
            "\t}",
            "\tint find(int x) {",
            "\t\twhile (x != f[x]) {",
            "\t\t\tx = f[x] = f[f[x]];",
            "\t\t}",
            "\t\treturn x;",
            "\t}",
            "\tbool same(int x, int y) {",
            "\t\treturn find(x) == find(y);",
            "\t}",
            "\tbool merge(int x, int y) {",
            "\t\tx = find(x);",
            "\t\ty = find(y);",
            "\t\tif (x == y) {",
            "\t\t\treturn false;",
            "\t\t}",
            "\t\tsiz[x] += siz[y];",
            "\t\tf[y] = x;",
            "\t\treturn true;",
            "\t}",
            "\tint size(int x) {",
            "\t\treturn siz[find(x)];",
            "\t}",
            "};", })
    }),
    s("FenwickTree", {
        t({
                "template<typename T>",
                "struct FenwickTree {",
                "    vector<T> a;",
                "    int n;",
                "",
                "    FenwickTree(int size) : n(size) {",
                "        a.assign(n, 0);",
                "    }",
                "",
                "    int lowbit(int x) {",
                "        return x & -x;",
                "    }",
                "",
                "    void update(int x, T d) {",
                "        while (x <= n) {",
                "            a[x] += d;",
                "            x += lowbit(x);",
                "        }",
                "    }",
                "",
                "    T query(int x) {",
                "        T res = 0;",
                "        while (x > 0) {",
                "            res += a[x];",
                "            x -= lowbit(x);",
                "        }",
                "        return res;",
                "    }",
                "};"
        })
    }),
})
